spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: servicio-equipos
          uri: lb://servicio-equipos
          predicates:
            - Path=/api/equipos/**
          filters:
            - StripPrefix=2
        - id: servicio-grupos
          uri: lb://servicio-grupos
          predicates:
            - Path=/api/grupos/**
          filters:
            - StripPrefix=2
        - id: servicio-partidos-apuestas
          uri: lb://servicio-partidos-apuestas
          predicates:
            - Path=/api/partidos-apuestas/datos/**
          filters:
              - StripPrefix=3
        - id: springboot-servicio-usuarios
          uri: lb://springboot-servicio-usuarios
          predicates:
            - Path=/api/usuarios/datos/**
          filters:
              - StripPrefix=3
        - id: servicio-oauth
          uri: lb://servicio-oauth
          predicates:
          - Path=/api/security/**
          filters:
          - StripPrefix=2